<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2r1adw3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2r1adw3/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2r1adw3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2r1adw3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2r1adw3\appProdProjectContainer([
    'container.build_hash' => '2r1adw3',
    'container.build_id' => 'e802f838',
    'container.build_time' => 1564733640,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2r1adw3');
